name: Spinalvote
main: com.spinalcraft.spinalvote.Spinalvote
version: 1.0

depend: [Spinalpack, Votifier]

commands:
  vote:
    description: Vote for the server on various websites.
    usage: /vote
    permission: spinalvote.vote
    permission-message: No!